#!/usr/bin/env python3
"""Generate per-file documentation for the workspace.

Produces markdown files under docs/files/ with extracted docstrings, classes,
functions and signatures for Python files and simple headings for JS/JSX files.

Usage: from the repo root run `python3 scripts/generate_file_docs.py`
"""
import ast
import os
from pathlib import Path
import re
import json


ROOT = Path.cwd()
OUT_DIR = ROOT / 'docs' / 'files'
OUT_DIR.mkdir(parents=True, exist_ok=True)


def parse_python(path: Path):
    try:
        src = path.read_text()
        mod = ast.parse(src)
    except Exception as e:
        return {"error": str(e)}

    docstring = ast.get_docstring(mod)
    classes = []
    funcs = []

    for node in mod.body:
        if isinstance(node, ast.ClassDef):
            methods = []
            bases = [ast.unparse(b) if hasattr(ast, 'unparse') else getattr(b, 'id', '') for b in node.bases]
            for m in node.body:
                if isinstance(m, ast.FunctionDef):
                    sig = f"def {m.name}({', '.join([a.arg for a in m.args.args])})"
                    mdoc = ast.get_docstring(m)
                    methods.append({"name": m.name, "signature": sig, "doc": (mdoc or '')})
            classes.append({"name": node.name, "bases": bases, "doc": ast.get_docstring(node) or '', "methods": methods})
        elif isinstance(node, ast.FunctionDef):
            args = []
            for a in node.args.args:
                if a.arg == 'self':
                    continue
                args.append(a.arg)
            sig = f"def {node.name}({', '.join(args)})"
            funcs.append({"name": node.name, "signature": sig, "doc": ast.get_docstring(node) or ''})

    exports = []
    # simple __all__ extraction
    allm = re.search(r"__all__\s*=\s*\[([^\]]*)\]", src, flags=re.S)
    if allm:
        exports = [s.strip().strip('\"\'') for s in allm.group(1).split(',') if s.strip()]

    return {"path": str(path.relative_to(ROOT)), "doc": docstring or '', "classes": classes, "functions": funcs, "exports": exports}


def parse_js(path: Path):
    src = path.read_text(errors='ignore')
    # grab top-level comment block
    m = re.search(r'/\*([\s\S]*?)\*/', src)
    doc = (m.group(1).strip() if m else '')
    # find exported functions and components
    exports = re.findall(r'export\s+(?:default\s+)?(?:function|const|class)\s+([A-Za-z0-9_]+)', src)
    return {"path": str(path.relative_to(ROOT)), "doc": doc, "exports": exports}


def generate_for_file(path: Path):
    if path.suffix in ('.py',):
        return parse_python(path)
    if path.suffix in ('.js', '.jsx', '.ts', '.tsx'):
        return parse_js(path)
    return None


def slugify(p: str) -> str:
    return re.sub(r'[^A-Za-z0-9\-]+', '-', p).strip('-')


def write_md(info: dict):
    if not info:
        return
    rel = info.get('path')
    out_path = OUT_DIR / (slugify(rel) + '.md')
    title = rel
    lines = []
    lines.append(f"# {title}\n")

    if 'error' in info:
        lines.append('> ⚠️ Failed to parse file: ' + info['error'] + '\n')
    if info.get('doc'):
        lines.append('## Module docstring\n')
        lines.append(info['doc'] + '\n')

    if info.get('exports'):
        lines.append('## Exports / top-level names\n')
        if info['exports']:
            for ex in info['exports']:
                lines.append(f'- {ex}\n')
        else:
            lines.append('- (no explicit exports detected)\n')

    if info.get('classes'):
        lines.append('## Classes\n')
        for c in info['classes']:
            lines.append(f"### {c['name']}\n")
            if c.get('bases'):
                lines.append('Bases: ' + ', '.join(c['bases']) + '\n')
            if c.get('doc'):
                lines.append(c['doc'] + '\n')
            if c.get('methods'):
                lines.append('Methods:\n')
                for m in c['methods']:
                    lines.append(f"- `{m['signature']}` — {m['doc'] or '(no doc)'}\n")

    if info.get('functions'):
        lines.append('## Functions\n')
        for f_ in info['functions']:
            lines.append(f"- `{f_['signature']}` — {f_['doc'] or '(no doc)'}\n")

    if info.get('path'):
        lines.append('\n---\n')
        lines.append(f"_Autogenerated: {info['path']}_\n")

    out_path.write_text('\n'.join(lines))
    return out_path


def gather_filelists():
    # Use find to gather both backend and frontend source files
    backend_files = (ROOT / 'backend' / 'app').rglob('*.py')
    frontend_files = (ROOT / 'engineering-portal-frontend' / 'src').rglob('*')
    files = []
    for f in backend_files:
        files.append(f)
    for f in frontend_files:
        if f.suffix in ('.js', '.jsx', '.ts', '.tsx'):
            files.append(f)
    return sorted(files, key=lambda p: str(p))


def main():
    files = gather_filelists()
    index = []
    for f in files:
        rel = str(f.relative_to(ROOT))
        print('Parsing', rel)
        info = generate_for_file(f)
        md = write_md(info)
        if md:
            index.append({'path': rel, 'md': str(md.relative_to(ROOT))})

    # write index
    idx_path = OUT_DIR / 'INDEX.md'
    with idx_path.open('w') as idxf:
        idxf.write('# Generated per-file docs\n\n')
        idxf.write('This folder contains an auto-generated documentation file for each source module (python/js/jsx).\n\n')
        for item in index:
            idxf.write(f"- [{item['path']}]({item['md']})\n")

    print('Wrote', len(index), 'files to', OUT_DIR)


if __name__ == '__main__':
    main()
